# Generated by Django 3.1.2 on 2020-11-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo del Equipo')),
                ('descripcion', models.TextField(verbose_name='Detalle del Equipo')),
                ('imagen', models.URLField(verbose_name='URL de la imagen')),
                ('estado', models.BooleanField(default=False, verbose_name='Disponible o No?')),
                ('ingresado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de ingreso')),
                ('Prestamo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de prestamo')),
            ],
        ),
    ]
