# Generated by Django 3.1.2 on 2020-11-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='Prestamo',
            new_name='prestamo',
        ),
        migrations.AlterField(
            model_name='equipo',
            name='estado',
            field=models.BooleanField(default=False, verbose_name='Disponible ?'),
        ),
    ]
