# Generated by Django 3.1.2 on 2020-11-11 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_auto_20201111_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=70, verbose_name='Nombre Completo')),
                ('Fechae', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de entrega')),
                ('fechad', models.DateField(verbose_name='Decha de Devolucion')),
                ('OperadorE', models.CharField(max_length=70, verbose_name='Operador Que Entrega')),
                ('OperadorR', models.CharField(max_length=70, verbose_name='Operador Que Recibe')),
                ('Observaciones', models.TextField(verbose_name='Observacion Del Equipo')),
                ('tipo', models.CharField(choices=[('E', 'Estudiante'), ('P', 'Profesor')], default='E', max_length=1)),
                ('Equipoo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipos.equipo')),
            ],
        ),
    ]
